/run/initialize
##/control/verbose 2
##/run/verbose 2
##/tracking/verbose 2#

## create from distribution hist (fast)
/gps/particle e-
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/file Sr90_Spectrum.dat
/gps/hist/inter Lin

## source position
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 0.79 mm
/gps/pos/centre 0. 0 -200 mm
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 32 deg
/gps/ang/minphi 0 deg
/gps/ang/maxphi 360 deg

/run/beamOn 1000000
